add CI for tiny_uart_baud_bit_gen_tb.vhd and tiny_uart_tb.vhd

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -37,8 +37,20 @@ jobs:
         run: |
           ghdl --version
           mkdir -p ./sim/work
-      - name: tiny_uart_inp_filter_tb
+      - name: tiny_uart_inp_filter
         run: |
           ghdl -a ${GHDL_OPTS} ./hdl/tiny_uart_inp_filter.vhd
           ghdl -a ${GHDL_OPTS} ./tb/tiny_uart_inp_filter_tb.vhd
           ((ghdl -r ${GHDL_OPTS} tiny_uart_inp_filter_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   tiny_uart_inp_filter_tb"; exit 1; fi)
+      - name: tiny_uart_baud_bit_gen
+        run: |
+          ghdl -a ${GHDL_OPTS} ./hdl/tiny_uart_baud_bit_gen.vhd
+          ghdl -a ${GHDL_OPTS} ./tb/tiny_uart_baud_bit_gen_tb.vhd
+          ((ghdl -r ${GHDL_OPTS} tiny_uart_baud_bit_gen_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   tiny_uart_baud_bit_gen_tb"; exit 1; fi)
+      - name: tiny_uart
+        run: |
+          ghdl -a ${GHDL_OPTS} ./hdl/tiny_uart_inp_filter.vhd
+          ghdl -a ${GHDL_OPTS} ./hdl/tiny_uart_baud_bit_gen.vhd
+          ghdl -a ${GHDL_OPTS} ./hdl/tiny_uart.vhd
+          ghdl -a ${GHDL_OPTS} ./tb/tiny_uart_tb.vhd
+          ((ghdl -r ${GHDL_OPTS} tiny_uart_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   tiny_uart_tb"; exit 1; fi)
